donors = [
    {
        "pseudonym": "donor0",
        "age": "23",
        "is_male": True,
        "is_prior_autologous_transplant": True,
        "donor_relation": "Unrelated",
        "underlying_disease": None,
        "is_malignant": False,
        "remission": "Not Applicable",
        "relapse_count": 0.01,
        "hla_a1": "HLA-A*02:01",
        "hla_a2": "HLA-A*02:01",
        "hla_b1": "HLA-A*02:01",
        "hla_b2": "HLA-A*02:01",
        "hla_c1": "HLA-A*02:01",
        "hla_c2": "HLA-A*02:01",
        "hla_drb11": "HLA-A*02:01",
        "hla_drb12": "HLA-A*02:01",
        "hla_dqa11": "HLA-A*02:01",
        "hla_dqa12": "HLA-A*02:01",
        "hla_dqb11": "HLA-A*02:01",
        "hla_dqb12": "HLA-A*02:01",
        "hla_dpa11": "HLA-A*02:01",
        "hla_dpa12": "HLA-A*02:01",
        "hla_dpb11": "HLA-A*02:01",
        "hla_dpb12": "HLA-A*02:01",
        "ab0_compatibility": "Full-Compatibility",
        "is_cmv": False,
        "is_ebv": False,
        "is_hhv6_igg": False,
        "is_hhv6_dna": False,
        "creatinine": 0.42,
        "ldh": 0.50,
        "thrombocytes": 62.5
    },
    {
        "pseudonym": "donor1",
        "age": "38",
        "is_male": False,
        "is_prior_autologous_transplant": False,
        "donor_relation": "Unrelated",
        "underlying_disease": None,
        "is_malignant": False,
        "remission": "Not Applicable",
        "relapse_count": 0.1,
        "hla_a1": "HLA-A*02:01",
        "hla_a2": "HLA-A*02:01",
        "hla_b1": "HLA-A*02:01",
        "hla_b2": "HLA-A*02:01",
        "hla_c1": "HLA-A*02:01",
        "hla_c2": "HLA-A*02:01",
        "hla_drb11": "HLA-A*02:01",
        "hla_drb12": "HLA-A*02:01",
        "hla_dqa11": "HLA-A*02:01",
        "hla_dqa12": "HLA-A*02:01",
        "hla_dqb11": "HLA-A*02:01",
        "hla_dqb12": "HLA-A*02:01",
        "hla_dpa11": "HLA-A*02:01",
        "hla_dpa12": "HLA-A*02:01",
        "hla_dpb11": "HLA-A*02:01",
        "hla_dpb12": "HLA-A*02:01",
        "ab0_compatibility": "Minor-Compatibility",
        "is_cmv": False,
        "is_ebv": True,
        "is_hhv6_igg": True,
        "is_hhv6_dna": True,
        "creatinine": 0.22,
        "ldh": 0.30,
        "thrombocytes": 82.5
    },
    {
        "pseudonym": "donor2",
        "age": "27",
        "is_male": True,
        "is_prior_autologous_transplant": False,
        "donor_relation": "Unrelated",
        "underlying_disease": "lung cancer",
        "is_malignant": True,
        "remission": "Partial - Remission",
        "relapse_count": 2,
        "hla_a1": "HLA-A*02:01",
        "hla_a2": "HLA-A*02:01",
        "hla_b1": "HLA-A*02:01",
        "hla_b2": "HLA-A*02:01",
        "hla_c1": "HLA-A*02:01",
        "hla_c2": "HLA-A*02:01",
        "hla_drb11": "HLA-A*02:01",
        "hla_drb12": "HLA-A*02:01",
        "hla_dqa11": "HLA-A*02:01",
        "hla_dqa12": "HLA-A*02:01",
        "hla_dqb11": "HLA-A*02:01",
        "hla_dqb12": "HLA-A*02:01",
        "hla_dpa11": "HLA-A*02:01",
        "hla_dpa12": "HLA-A*02:01",
        "hla_dpb11": "HLA-A*02:01",
        "hla_dpb12": "HLA-A*02:01",
        "ab0_compatibility": "Bidirectional-Incompatibility",
        "is_cmv": True,
        "is_ebv": True,
        "is_hhv6_igg": False,
        "is_hhv6_dna": False,
        "creatinine": 0.12,
        "ldh": 0.20,
        "thrombocytes": 42.5
    }
]